import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Relógio Eclipse Minimalist",
    description: "Um relógio de luxo com design atemporal, pulseira de metal escovado e visor de safira.",
    price: 4500,
    image: "/src/assets/images/luxury_watch_product_1779193227417.png",
    category: "Relógios",
    material: "Aço Inoxidável",
    collection: "Celestial",
    isPremium: true
  },
  {
    id: "6",
    name: "Classic Gold Heritage",
    description: "Relógio clássico em ouro com pulseira de couro legítimo marrom.",
    price: 3800,
    image: "/src/assets/images/classic_gold_watch_1779199605568.png",
    category: "Relógios",
    material: "Ouro Amarelo / Couro",
    collection: "Heritage",
    isPremium: false
  },
  {
    id: "7",
    name: "Sport Carbon Pro",
    description: "Design moderno em fibra de carbono e pulseira de borracha de alta resistência.",
    price: 2900,
    image: "/src/assets/images/sport_black_watch_1779199626024.png",
    category: "Relógios",
    material: "Fibra de Carbono",
    collection: "Sport",
    isPremium: false
  },
  {
    id: "8",
    name: "Chronograph Ocean Blue",
    description: "Cronógrafo elegante com mostrador azul e pulseira de metal.",
    price: 5200,
    image: "/src/assets/images/chronograph_silver_watch_1779199638889.png",
    category: "Relógios",
    material: "Aço Inoxidável",
    collection: "Maritime",
    isPremium: true
  },
  {
    id: "9",
    name: "Rose Pearl Lady",
    description: "Luxo feminino em ouro rosa com detalhes em diamante e pérola.",
    price: 8900,
    image: "/src/assets/images/rose_gold_ladies_watch_1779199654149.png",
    category: "Relógios",
    material: "Ouro Rosa / Diamante",
    collection: "Elegance",
    isPremium: true
  },
  {
    id: "10",
    name: "Skeleton Artisan",
    description: "Mostrador esqueleto que revela o complexo mecanismo automático artesanal.",
    price: 15400,
    image: "/src/assets/images/skeleton_automatic_watch_1779199670998.png",
    category: "Relógios",
    material: "Titânio / Safira",
    collection: "Artisan",
    isPremium: true
  },
  {
    id: "11",
    name: "Titanium Explorer",
    description: "Relógio de campo robusto em titânio com pulseira tática militar.",
    price: 2450,
    image: "/src/assets/images/titanium_field_watch_image_1779199686641.png",
    category: "Relógios",
    material: "Titânio",
    collection: "Adventure",
    isPremium: false
  },
  {
    id: "12",
    name: "Midnight Minimalist",
    description: "Design ultra-fino em preto absoluto para ocasiões formais.",
    price: 3100,
    image: "/src/assets/images/minimalist_black_dress_watch_1779199701580.png",
    category: "Relógios",
    material: "Aço Escovado",
    collection: "Midnight",
    isPremium: false
  },
  {
    id: "13",
    name: "Diver Deep Sea",
    description: "Relógio de mergulho profissional com bisel de cerâmica e resistência extrema.",
    price: 6800,
    image: "/src/assets/images/diver_blue_watch_image_test_1779199715154.png",
    category: "Relógios",
    material: "Aço / Cerâmica",
    collection: "Deep Sea",
    isPremium: true
  },
  {
    id: "14",
    name: "Vintage Mechanical",
    description: "O charme do passado com mecanismo de corda manual e couro envelhecido.",
    price: 4200,
    image: "/src/assets/images/vintage_mechanical_watch_1779199732481.png",
    category: "Relógios",
    material: "Bronze / Couro",
    collection: "Vintage",
    isPremium: false
  },
  {
    id: "2",
    name: "Anel Solitário Aurora",
    description: "Diamante lapidado à mão montado em ouro branco 18k. O símbolo máximo de elegância.",
    price: 12000,
    image: "/src/assets/images/diamond_ring_product_1779193242696.png",
    category: "Anéis",
    material: "Ouro Branco / Diamante",
    collection: "Eternity",
    isPremium: true
  },
  {
    id: "15",
    name: "Anel Crystal Bloom",
    description: "Anel delicado com detalhes em cristal que lembram flores.",
    price: 1500,
    image: "/src/assets/images/luxury_rings_collection_1_1779200079927.png",
    category: "Anéis",
    material: "Prata 950",
    collection: "Bloom",
    isPremium: false
  },
  {
    id: "16",
    name: "Anel Royal Sapphire",
    description: "Uma safira central rodeada de diamantes em ouro nobre.",
    price: 18000,
    image: "/src/assets/images/luxury_rings_collection_2_1779200094812.png",
    category: "Anéis",
    material: "Ouro Nobre / Safira",
    collection: "Royal",
    isPremium: true
  },
  {
    id: "17",
    name: "Anel Minimalist Pearl",
    description: "Design contemporâneo com pérola natural.",
    price: 2200,
    image: "/src/assets/images/luxury_rings_collection_2_1779200094812.png",
    category: "Anéis",
    material: "Ouro Amarelo",
    collection: "Elements",
    isPremium: false
  },
  {
    id: "18",
    name: "Anel Starry Night",
    description: "Pequenos diamantes cravados que lembram o céu estrelado.",
    price: 4500,
    image: "/src/assets/images/Anel Starry Night.png",
    category: "Anéis",
    material: "Ouro Branco",
    collection: "Galaxy",
    isPremium: false
  },
  {
    id: "19",
    name: "Anel Emerald Dream",
    description: "Esmeralda lapidada em formato gota.",
    price: 25000,
    image: "/src/assets/images/luxury_rings_collection_1_1779200079927.png",
    category: "Anéis",
    material: "Ouro 18k / Esmeralda",
    collection: "Dream",
    isPremium: true
  },
  {
    id: "20",
    name: "Anel Golden Twist",
    description: "Design torcido em ouro 18k.",
    price: 1800,
    image: "/src/assets/images/luxury_rings_collection_2_1779200094812.png",
    category: "Anéis",
    material: "Ouro Amarelo",
    collection: "Dunes",
    isPremium: false
  },
  {
    id: "21",
    name: "Anel Diamond Halo",
    description: "Diamante central com halo de brilhantes.",
    price: 15000,
    image: "/src/assets/images/Anel Diamont Halo.png",
    category: "Anéis",
    material: "Ouro Branco",
    collection: "Eternity",
    isPremium: true
  },
  {
    id: "22",
    name: "Anel Rose Quartz",
    description: "Quartzo rosa para um toque romântico.",
    price: 3200,
    image: "/src/assets/images/Anel Rose Quartz.png",
    category: "Anéis",
    material: "Ouro Rosa",
    collection: "Passion",
    isPremium: false
  },
  {
    id: "23",
    name: "Anel Eternity Band",
    description: "Banda cravejada com diamantes em toda a volta.",
    price: 12500,
    image: "/src/assets/images/Anel Eternity Band.png",
    category: "Anéis",
    material: "Platina / Diamante",
    collection: "Eternity",
    isPremium: true
  },
  {
    id: "3",
    name: "Colar Golden Sands",
    description: "Colar de ouro 18k com design fluido inspirado nas dunas do deserto.",
    price: 3200,
    image: "/src/assets/images/gold_necklace_product_1779193254767.png",
    category: "Colares",
    material: "Ouro Amarelo 18k",
    collection: "Dunes",
    isPremium: false
  },
  {
    id: "24",
    name: "Colar Diamond Drop",
    description: "Pingente de diamante em formato gota.",
    price: 7500,
    image: "/src/assets/images/luxury_necklaces_collection_1_1779200109963.png",
    category: "Colares",
    material: "Ouro Branco",
    collection: "Celestial",
    isPremium: true
  },
  {
    id: "25",
    name: "Colar Pearl Essence",
    description: "Pérola única de água doce em corrente fina.",
    price: 1200,
    image: "/src/assets/images/luxury_necklaces_collection_2_1779200124863.png",
    category: "Colares",
    material: "Prata 950",
    collection: "Elements",
    isPremium: false
  },
  {
    id: "26",
    name: "Colar Ruby Star",
    description: "Rubi central em formato de estrela.",
    price: 9800,
    image: "/src/assets/images/luxury_necklaces_collection_1_1779200109963.png",
    category: "Colares",
    material: "Ouro 18k / Rubi",
    collection: "Galaxy",
    isPremium: true
  },
  {
    id: "27",
    name: "Colar Silver Layers",
    description: "Colar em camadas para um look moderno.",
    price: 850,
    image: "/src/assets/images/luxury_necklaces_collection_2_1779200124863.png",
    category: "Colares",
    material: "Prata Esterlina",
    collection: "Nordic",
    isPremium: false
  },
  {
    id: "28",
    name: "Colar Infinity Loop",
    description: "Símbolo do infinito cravejado com brilhantes.",
    price: 2400,
    image: "/src/assets/images/luxury_necklaces_collection_1_1779200109963.png",
    category: "Colares",
    material: "Ouro Amarelo",
    collection: "Eternity",
    isPremium: false
  },
  {
    id: "29",
    name: "Colar Moon Phase",
    description: "Representação das fases da lua.",
    price: 1600,
    image: "/src/assets/images/luxury_necklaces_collection_2_1779200124863.png",
    category: "Colares",
    material: "Prata 950",
    collection: "Celestial",
    isPremium: false
  },
  {
    id: "30",
    name: "Colar Emerald pendant",
    description: "Esmeralda quadrada envolta em ouro branco.",
    price: 14500,
    image: "/src/assets/images/luxury_necklaces_collection_1_1779200109963.png",
    category: "Colares",
    material: "Ouro Branco / Esmeralda",
    collection: "Artisan",
    isPremium: true
  },
  {
    id: "31",
    name: "Colar Rose Bloom",
    description: "Rosácea em ouro rosa.",
    price: 3100,
    image: "/src/assets/images/luxury_necklaces_collection_2_1779200124863.png",
    category: "Colares",
    material: "Ouro Rosa",
    collection: "Bloom",
    isPremium: false
  },
  {
    id: "32",
    name: "Colar Choker Velvet",
    description: "Gargantilha com detalhe em diamante.",
    price: 5200,
    image: "/src/assets/images/luxury_necklaces_collection_1_1779200109963.png",
    category: "Colares",
    material: "Ouro / Veludo",
    collection: "Midnight",
    isPremium: true
  },
  {
    id: "4",
    name: "Brincos Cristal de Gelo",
    description: "Brincos de prata esterlina com cristais selecionados para um brilho incomparável.",
    price: 850,
    image: "/src/assets/images/ice_crystal_earrings_1779194138434.png",
    category: "Brincos",
    material: "Prata 950",
    collection: "Nordic",
    isPremium: false
  },
  {
    id: "33",
    name: "Brincos Diamond Studs",
    description: "Brilhantes solitários clássicos.",
    price: 12000,
    image: "/src/assets/images/luxury_earrings_collection_1_1779200138503.png",
    category: "Brincos",
    material: "Platina / Diamante",
    collection: "Eternity",
    isPremium: true
  },
  {
    id: "34",
    name: "Brincos Gold Hoops",
    description: "Argolas clássicas em ouro 18k.",
    price: 2100,
    image: "/src/assets/images/luxury_earrings_collection_2_1779200151680.png",
    category: "Brincos",
    material: "Ouro Amarelo",
    collection: "Elegance",
    isPremium: false
  },
  {
    id: "35",
    name: "Brincos Chandelier Pearl",
    description: "Brincos pendentes com pérolas.",
    price: 5800,
    image: "/src/assets/images/luxury_earrings_collection_1_1779200138503.png",
    category: "Brincos",
    material: "Ouro Branco / Pérola",
    collection: "Royal",
    isPremium: true
  },
  {
    id: "36",
    name: "Brincos Minimalist bar",
    description: "Design moderno em barra de prata.",
    price: 450,
    image: "/src/assets/images/luxury_earrings_collection_2_1779200151680.png",
    category: "Brincos",
    material: "Prata 950",
    collection: "Nordic",
    isPremium: false
  },
  {
    id: "37",
    name: "Brincos Sapphire Drop",
    description: "Safiras pendentes envoltas em brilhantes.",
    price: 19500,
    image: "/src/assets/images/luxury_earrings_collection_1_1779200138503.png",
    category: "Brincos",
    material: "Ouro Nobre / Safira",
    collection: "Artisan",
    isPremium: true
  },
  {
    id: "38",
    name: "Brincos Rose Petals",
    description: "Formato de pétalas em ouro rosa.",
    price: 2800,
    image: "/src/assets/images/luxury_earrings_collection_2_1779200151680.png",
    category: "Brincos",
    material: "Ouro Rosa",
    collection: "Bloom",
    isPremium: false
  },
  {
    id: "39",
    name: "Brincos Starry Night",
    description: "Pequenas estrelas com zircônias.",
    price: 650,
    image: "/src/assets/images/luxury_earrings_collection_2_1779200151680.png",
    category: "Brincos",
    material: "Prata Esterlina",
    collection: "Galaxy",
    isPremium: false
  },
  {
    id: "40",
    name: "Brincos Emerald Studs",
    description: "Esmeraldas quadradas solitárias.",
    price: 15600,
    image: "/src/assets/images/luxury_earrings_collection_1_1779200138503.png",
    category: "Brincos",
    material: "Ouro Amarelo / Esmeralda",
    collection: "Eternity",
    isPremium: true
  },
  {
    id: "41",
    name: "Brincos Midnight Onyx",
    description: "Ônix negra lapidada em metal escuro.",
    price: 3400,
    image: "/src/assets/images/luxury_earrings_collection_1_1779200138503.png",
    category: "Brincos",
    material: "Aço / Ônix",
    collection: "Midnight",
    isPremium: false
  },
  {
    id: "5",
    name: "Pulseira Ocean Breeze",
    description: "Pulseira elegante com detalhes em safira e ouro branco.",
    price: 2800,
    image: "/src/assets/images/ocean_breeze_bracelet_1779194120139.png",
    category: "Pulseiras",
    material: "Ouro Branco / Safira",
    collection: "Deep Sea",
    isPremium: false
  },
  {
    id: "42",
    name: "Pulseira Diamond Link",
    description: "Elos de ouro cravejados com diamantes.",
    price: 22000,
    image: "/src/assets/images/luxury_bracelets_collection_1_1779200168054.png",
    category: "Pulseiras",
    material: "Ouro Amarelo / Diamante",
    collection: "Royal",
    isPremium: true
  },
  {
    id: "43",
    name: "Pulseira Silver Cuff",
    description: " Bracelete rígido em prata lisa.",
    price: 1100,
    image: "/src/assets/images/luxury_bracelets_collection_2_1779200183559.png",
    category: "Pulseiras",
    material: "Prata 950",
    collection: "Nordic",
    isPremium: false
  },
  {
    id: "44",
    name: "Pulseira Rose charms",
    description: "Pulseira de ouro rosa com berloques variados.",
    price: 4900,
    image: "/src/assets/images/rose_charms_bracelet_1779239139645.png",
    category: "Pulseiras",
    material: "Ouro Rosa",
    collection: "Passion",
    isPremium: false
  },
  {
    id: "45",
    name: "Pulseira Minimalist bar",
    description: "Corrente fina com detalhe em barra.",
    price: 950,
    image: "/src/assets/images/luxury_bracelets_collection_2_1779200183559.png",
    category: "Pulseiras",
    material: "Prata Esterlina",
    collection: "Elements",
    isPremium: false
  },
  {
    id: "46",
    name: "Pulseira Golden Knot",
    description: "Design de nó em ouro 18k.",
    price: 3600,
    image: "/src/assets/images/luxury_bracelets_collection_1_1779200168054.png",
    category: "Pulseiras",
    material: "Ouro Amarelo",
    collection: "Dunes",
    isPremium: false
  },
  {
    id: "47",
    name: "Pulseira Starry Night",
    description: "Pequenos astros em ouro branco.",
    price: 5400,
    image: "/src/assets/images/luxury_bracelets_collection_1_1779200168054.png",
    category: "Pulseiras",
    material: "Ouro Branco",
    collection: "Galaxy",
    isPremium: true
  },
  {
    id: "48",
    name: "Pulseira Pearl Strand",
    description: "Fileira de mini pérolas naturais.",
    price: 1800,
    image: "/src/assets/images/luxury_bracelets_collection_2_1779200183559.png",
    category: "Pulseiras",
    material: "Ouro Amarelo / Pérola",
    collection: "Elements",
    isPremium: false
  },
  {
    id: "49",
    name: "Pulseira Midnight Bangle",
    description: "Bracelete em metal escurecido.",
    price: 2700,
    image: "/src/assets/images/luxury_bracelets_collection_2_1779200183559.png",
    category: "Pulseiras",
    material: "Aço Black",
    collection: "Midnight",
    isPremium: false
  },
  {
    id: "50",
    name: "Pulseira Emerald Line",
    description: "Linha de esmeraldas lapidadas.",
    price: 28500,
    image: "/src/assets/images/luxury_bracelets_collection_1_1779200168054.png",
    category: "Pulseiras",
    material: "Ouro Branco / Esmeralda",
    collection: "Artisan",
    isPremium: true
  }
];

export const HERO_IMAGE = "/src/assets/images/hero_jewelry_banner_1779193212908.png";
